# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo_id',
            new_name='dojo',
        ),
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
